# Generated by Django 6.0.4 on 2026-04-28 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=255)),
                ('child_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='chat_analyzer.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of message from whatsapp')),
                ('time', models.TimeField(help_text='Time of the message from whatsapp')),
                ('username', models.CharField(help_text='original sender name/ number from whatsapp', max_length=200)),
                ('message', models.TextField(help_text='original message text')),
                ('cleaned_text', models.TextField(blank=True, help_text='cleaned version (after preprocessing)', null=True)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='sentiment analysis result', max_length=20, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='when this was imported')),
                ('upload_batch', models.CharField(blank=True, help_text='Batch ID for grouping uploads', max_length=100, null=True)),
                ('client', models.ForeignKey(help_text='the client this conversation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat_analyzer.client')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Converstions',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapists', to='chat_analyzer.admin')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='assigned_therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='chat_analyzer.therapist'),
        ),
    ]
