# Generated by Django 6.0.4 on 2026-05-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin and Staff'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client of Autism Center'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
