# Generated by Django 6.0.4 on 2026-08-13 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='upload_by',
            new_name='uploaded_by',
        ),
    ]
