# Generated by Django 6.0.4 on 2026-05-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_analyzer', '0002_alter_admin_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmatchedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('username', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_batch', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Unmatched Message',
                'verbose_name_plural': 'Unmatched Messages',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
