# Generated by Django 6.0.4 on 2026-08-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_analyzer', '0002_rename_upload_by_conversation_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='sentiment_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score from 0.0 to 1.0', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='Sentiment score from -1.0 to +1.0', null=True),
        ),
    ]
