# Generated by Django 6.0.4 on 2026-08-16 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_analyzer', '0003_conversation_sentiment_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_from_client',
            field=models.BooleanField(default=True, help_text='True if message is from client, False if from therapist/staff'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Who sent this message (client, therapist, or admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('client', 'message_hash')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client', 'date'], name='chat_analyz_client__fc586c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['sender', 'is_from_client'], name='chat_analyz_sender__ad0506_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['upload_batch'], name='chat_analyz_upload__9622f1_idx'),
        ),
    ]
