# Generated by Django 6.0.4 on 2026-05-17 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_analyzer', '0003_unmatchedmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='assigned_therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='chat_analyzer.therapist'),
        ),
    ]
