# Generated by Django 6.0.4 on 2026-08-16 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_analyzer', '0004_conversation_is_from_client_conversation_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='therapist',
            field=models.ForeignKey(blank=True, help_text='The therapist involve in this conversation (if therapist sent message)', limit_choices_to={'role': 'therapist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapist_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
