# Generated by Django 6.0.4 on 2026-08-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_analyzer', '0005_conversation_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='cleaned_text_topic',
            field=models.TextField(blank=True, help_text='Cleaned version for topic modeling (aggressive one)', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_cleaned_sentiment',
            field=models.BooleanField(default=False, help_text='Has this message been cleaned for sentiment analysis ?'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_cleaned_topic',
            field=models.BooleanField(default=False, help_text='Has this message been cleaned for topic modeling ??'),
        ),
    ]
