# Generated by Django 6.0.4 on 2026-08-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_analyzer', '0006_conversation_cleaned_text_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetopic',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Is this primary topic for this message ?'),
        ),
    ]
