# Generated by Django 6.0.4 on 2026-09-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_analyzer', '0007_messagetopic_is_primary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['status', 'name'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics 🧠'},
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('active', 'Active — used in clinical reports'), ('discovered', 'Auto-discovered — awaiting review'), ('archived', 'Archived — historical only')], default='active', help_text='Active = used in reports. Discovered = needs review. Archived = retired.', max_length=20),
        ),
    ]
