# Generated by Django 6.1.1 on 2026-10-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_analyzer', '0008_alter_topic_options_topic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttopicscore',
            name='message_count',
            field=models.IntegerField(default=0, help_text='Number of message assign to this topic'),
        ),
    ]
