# Generated by Django 6.1.1 on 2026-10-06 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_analyzer', '0009_clienttopicscore_message_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisdocument',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='diagnosisdocument',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='diagnosisdocument',
            name='file_size',
        ),
        migrations.AddField(
            model_name='diagnosisdocument',
            name='file',
            field=models.FileField(blank=True, help_text='Allowed: PDF, DOCX, PNG, JPG', null=True, upload_to='diagnosis_documents/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
