# Generated by Django 6.1.1 on 2026-10-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_analyzer', '0010_remove_diagnosisdocument_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterspecifier',
            name='definition',
            field=models.TextField(blank=True, help_text='Plain English explanation of this specifier', null=True),
        ),
    ]
